---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webappdeploy
  labels:
    app: webapp
spec:
  selector:
    matchLabels:
      app: webapp 
  replicas: 2 
  template:
    metadata:
      name: fbpod
      labels:
        app: webapp
    spec:
      containers:
        - name: webcont
          image: ramanijadala/webapp:tag
          ports:
            - containerPort: 8080
---

---
apiVersion: v1 
kind: Service
metadata:
  name: webapp-svc 
  labels:
    app: webapp
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: webapp
