name: Deploy to Tomcat via Manager API

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '11'

      - name: Build WAR using Maven
        run: mvn clean package -DskipTests

      - name: Deploy WAR to Tomcat
       
        run: |
          WAR_FILE=$(ls target/*.war | head -n 1)
          echo "Deploying $WAR_FILE to Tomcat..."
          curl -u tomcat:tomcat \
            --upload-file "$WAR_FILE" \
            "http://54.92.193.98:8080/manager/text/deploy?path=/myapp&update=true"

