name: Deploy to Tomcat via Manager API

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Build WAR using Maven
        run: mvn clean package -DskipTests

      - name: Deploy WAR to Tomcat
        run: |
          WAR_FILE=$(ls target/*.war | head -n 1)
          APP_NAME=myapp  # change this if you want a different context path
          
          curl -u ${{ secrets.TOMCAT_USER }}:${{ secrets.TOMCAT_PASSWORD }} \
            -T "$WAR_FILE" \
            "http://${{ secrets.TOMCAT_HOST }}:8080/manager/text/deploy?path=/$APP_NAME&update=true"
